### ISSUE TITLE
Saving to output file (gpkg) fails for all tools (that have that option)

### ISSUE THREAD

**Issue by japeki** [GispoCoding/kimu#63]
@nmaarnio For some reason saving to existing file doesn't work. It worked in previous releases. QGIS gives an error:

2022-12-16T14:52:25     WARNING    Traceback (most recent call last): File "C:/Users/<user>/AppData/Roaming/QGIS/QGIS3\profiles\<user>/python/plugins\kimu\plugin.py", line 230, in activate_intersection_tool_lines self.intersection_tool_lines.run()File "C:/Users/<user>/AppData/Roaming/QGIS/QGIS3\profiles\<user>/python/plugins\kimu\core\intersection_tool_lines.py", line 470, in run write_output_to_file(result_layer, output_path) File "C:/Users/<user>/AppData/Roaming/QGIS/QGIS3\profiles\<user>/python/plugins\kimu\core\tool_functions.py", line 121, in write_output_to_file error, explanation, _, _ = QgsVectorFileWriter.writeAsVectorFormatV3(AttributeError: type object 'QgsVectorFileWriter' has no attribute 'writeAsVectorFormatV3'

**Comment by nmaarnio** [comment]
I had upgraded the writer function to V3 as QGIS suggested. Are you using older QGIS version than 3.20? I think this should be a versioning problem. Anyway, I reverted back to V2 writer now which should work in all 3.00 -> versions, it just might throw some deprecations warnings in the newest QGIS versions.

**Comment by japeki** [comment]
Yes, we are  still using 3.16. We will probably have to agree later on updating policy as we move to newer versions.
